#ifndef MIDI_COMMON_H
#define MIDI_COMMON_H
typedef enum midi_error_code
{
	MIDI_ERR_NO_ERROR=0,
	MIDI_ERR_OPEN_FILE,
	MIDI_ERR_CLOSE_FILE,
	MIDI_ERR_REOPEN_FILE,
	MIDI_ERR_SEEK_TRACK,
	MIDI_ERR_MALFORMED_TEMPO,
	MIDI_ERR_EARLY_END_OF_TRACK,
	MIDI_ERR_MISALIGNED_TRACK,
	MIDI_ERR_CORRUPTED_FILE_HEADER,
	MIDI_ERR_CORRUPTED_TRACK_HEADER,
	MIDI_ERR_READING_EVENT,
	MIDI_ERR_WRITING_EVENT,
	MIDI_ERR_OUT_OF_MEMORY,
	MIDI_ERR_FINALIZING,
	MIDI_ERR_WRITING_HEADER,
	MIDI_MAX_ERROR
} midi_error_code;


void print_midi_error	(int errnum);
#endif
