Document: lv2file
Title: Debian lv2file Manual
Author: <insert document author here>
Abstract: This manual describes what lv2file is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lv2file/lv2file.sgml.gz

Format: postscript
Files: /usr/share/doc/lv2file/lv2file.ps.gz

Format: text
Files: /usr/share/doc/lv2file/lv2file.text.gz

Format: HTML
Index: /usr/share/doc/lv2file/html/index.html
Files: /usr/share/doc/lv2file/html/*.html
