.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH LV2FILE 1 "March 14, 2011"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
lv2file \- Apply LV2 effects to audio files
.SH SYNOPSIS
.B lv2file
.RS
.RI \-l|\-\-list
.br
\-n|\-\-nameports
.I PLUGIN
.br
.RI \-i
.I INFILE
-o
.I OUTFILE
[
.I OPTIONS
]
.I PLUGIN
.RE
.SH DESCRIPTION
lv2file is aprogram which you can use to apply effects to your audio files without much hassle. Possible use cases are:
.RS
* To apply an effect without having to open a GUI or start a project.
.br
* To apply effects to a large number of files, or in an automated manner.
.br
* A deterministic environment to debug a plugin.
.br
* Audio editing in a command-line only environment 
.RE
.br
lv2file uses the LV2 plugin format (http://lv2plug.in/) for the effects it uses. 
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-l, \-\-list
List all available plugins.
.TP
.B \-n \-\-nameports \fIPLUGIN\fR
List all the input and control ports for the specified plugin.
.TP
.B \-i \fIFILE\fR
Input the audio from a given FILE.  Most common sampled audio formats are supported.
.TP
.B \-o \fIFILE\fR
Output to given FILE.
.TP
.B \-c, \-\-connect \fICHANNEL\fR:\fIPORT\fR
Connect the channel CHANNEL in the input file to the audio port PORT of the plugin.
If you connect multiple channels to the same port, they will be mixed together.
The -c option is often not necessary, as lv2file will try to guess how you would like to connect the ports.
.br
It is possible to run multiple instances of a plugin using the syntax "-c 5:2.left" which, for example, would connect the fifth channel of audio to the port labeled "left" in the second copy of the plugin.
You don't need to specify how many plugins to run, lv2file automatically makes enough according to the connections you make. 
.TP
.B \-p, \-\-parameters \fIPORT\fR:\fIVALUE\fR
Pass values to the control ports of the plugin, essentially telling the effect how to handle the audio.
PORT is the name of the control port, and VALUE is the value to set it to.
For example "-p volume:1" sets the effects "volume" control to 1.

You should note that because lv2file uses LV2 plugins, the VALUES will always be floating point numbers.
It is not possible to vary a parameter with time.
It is also not possible to have different control values for multiple plugin instances.
Instead, split up the channels of your audio files, and process them in batches whose parameters are all the same.
.TP
.B [ \-m \-\-mono ]
Mix down all of the channels together and pass them to the plugin. This will only work if the plugin has only a single audio input. This is to be used instead of manually specifying connections.
.TP
.B [ \-b, \-\-blocksize \fIN\fR ]
The size of the chunks the audio is processed in.
This might have implications for speed of processing.
.I N
is measured in frames, not samples.  The default is 512.

.SH AUTHOR
lv2file was written by Jeremy Salwen <jeremysalwen@gmail.com>.
.PP
This manual page was written by Jeremy Salwen <jeremysalwen@gmail.com>,
for the Debian project (and may be used by others).
